### ISSUE TITLE
[Bug] Typescript template broken

### ISSUE THREAD

**Issue by Alxandr** [react-static/react-static#1263]
I ran `react-static create`, selected the typescript template, and then ran `start` command. This was the result:

![image](https://user-images.githubusercontent.com/112334/61406982-52172c80-a8dd-11e9-9ba7-5c93d6dca1ec.png)

### Environment

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

```

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 53.27 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.1
  npmPackages:
    react: ^16.8.2 => 16.8.6 
    react-dom: ^16.8.2 => 16.8.6 
    react-static: ^7.0.0 => 7.0.5 
    react-static-plugin-reach-router: latest => 7.0.10 
    react-static-plugin-sitemap: latest => 7.0.10 
    react-static-plugin-source-filesystem: latest => 7.1.0 
    react-static-plugin-typescript: latest => 7.0.10 
  npmGlobalPackages:
    react-static: 7.1.0

```

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  `react-static start`

### Expected Behavior

It should not fail.

### Reproducible Demo

Base typescript template. No modifications.

**Comment by SleeplessByte** [comment]
Some of the errors are fixed in https://github.com/react-static/react-static/pull/1181/files#diff-d7e32e53a0cf3628c5fe6d6cc10c8e29R11.

**Comment by Alxandr** [comment]
Sure. But it's not released/done yet. And you said "some" of the errors? I'd argue that having the OOB experience not working is quite critical, and an easy way to turn people away from the project. I'd recommend removing typescript template as an option till this is fixed, or fixing it asap (the first one probably being more feasible).

**Comment by SleeplessByte** [comment]
>  And you said "some" of the errors?

Without trying it out, I can not say with certainty that it will fix _all_ the issues. I am certain it will fix some of the errors 🗡 .

> I'd recommend removing typescript template as an option till this is fixed

Removing a template each time there is a breaking 💥 bug 🐛 isn't really a great experience for anyone either. This should just be fixed. If you look at #1259 and #1262 this is on the ⬆️ high priority list!

**Comment by gmosx** [comment]
The `TypeScript` template still doesn't work :(

Fortunately, a simple `yarn upgrade` afterwards fixes the issues.

**Comment by cloverich** [comment]
The template worked OOTB for me on macos, after `yarn global add react-static; react-static create`

```
me~ react-static -v
7.2.2
me~ node -v
v10.16.1
```

**Comment by DominikGuzei** [comment]
The Typescript template worked without any issues for me on osx Catalina.
